# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Wagr' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ADAL', '~> 2.2'
  # Pods for Wagr

end
